# Generated by Django 5.0.6 on 2024-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desc', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
